import type { Property } from "@/types/property"
import type { DoorAccessLog } from "@/types/door-access-log"

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "台北市中心現代公寓",
    description: "位於台北市中心的現代化公寓，交通便利，周邊生活機能完善。",
    type: "apartment",
    price: 2500,
    location: "信義區",
    city: "台北",
    country: "台灣",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    images: ["/modern-apartment-living-room.png", "/modern-bedroom.png"],
    amenities: ["WiFi", "空調", "廚房", "洗衣機", "電視"],
    hostId: "host1",
    hostName: "王小明",
    rating: 4.8,
    reviews: 124,
    available: true,
  },
  {
    id: "2",
    title: "海景別墅度假屋",
    description: "坐擁無敵海景的豪華別墅，適合家庭度假或朋友聚會。",
    type: "villa",
    price: 8000,
    location: "墾丁",
    city: "屏東",
    country: "台灣",
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    images: ["/luxury-villa-ocean-view.jpg", "/luxury-villa-pool.png"],
    amenities: ["WiFi", "空調", "游泳池", "停車場", "海景", "烤肉區"],
    hostId: "host2",
    hostName: "李美華",
    rating: 4.9,
    reviews: 89,
    available: true,
  },
  {
    id: "3",
    title: "溫馨工作室套房",
    description: "適合單人或情侶的溫馨工作室，設備齊全，拎包入住。",
    type: "studio",
    price: 1500,
    location: "東區",
    city: "台中",
    country: "台灣",
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    images: ["/cozy-studio-apartment.png", "/studio-kitchen.jpg"],
    amenities: ["WiFi", "空調", "廚房", "洗衣機"],
    hostId: "host3",
    hostName: "陳大偉",
    rating: 4.7,
    reviews: 56,
    available: true,
  },
  {
    id: "4",
    title: "山景獨棟別墅",
    description: "被大自然環繞的獨棟別墅，遠離塵囂，享受寧靜時光。",
    type: "house",
    price: 5500,
    location: "陽明山",
    city: "台北",
    country: "台灣",
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    images: ["/mountain-house-exterior.jpg", "/house-living-room-mountain-view.jpg"],
    amenities: ["WiFi", "空調", "廚房", "停車場", "山景", "庭院"],
    hostId: "host4",
    hostName: "張雅婷",
    rating: 4.9,
    reviews: 72,
    available: true,
  },
  {
    id: "5",
    title: "市中心豪華公寓",
    description: "高樓層豪華公寓，俯瞰城市美景，設施完善。",
    type: "apartment",
    price: 3500,
    location: "西門町",
    city: "台北",
    country: "台灣",
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    images: ["/luxury-apartment-city-view.jpg", "/modern-apartment-bedroom.png"],
    amenities: ["WiFi", "空調", "廚房", "健身房", "電梯", "城市景觀"],
    hostId: "host5",
    hostName: "林志明",
    rating: 4.6,
    reviews: 98,
    available: true,
  },
  {
    id: "6",
    title: "古城區傳統民宿",
    description: "保留傳統建築特色的民宿，體驗在地文化。",
    type: "house",
    price: 2000,
    location: "安平",
    city: "台南",
    country: "台灣",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    images: ["/traditional-taiwanese-house.jpg", "/traditional-bedroom.jpg"],
    amenities: ["WiFi", "空調", "廚房", "庭院"],
    hostId: "host6",
    hostName: "黃淑芬",
    rating: 4.8,
    reviews: 67,
    available: true,
  },
]

export function getPropertyById(id: string): Property | undefined {
  return mockProperties.find((p) => p.id === id)
}

export const mockDoorAccessLogs: DoorAccessLog[] = [
  {
    id: "log1",
    bookingId: "booking1",
    propertyId: "1",
    propertyTitle: "台北市中心現代公寓",
    userId: "user1",
    userName: "張三",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    action: "unlock",
    status: "success",
    deviceInfo: "iPhone 14 Pro",
    location: "台北市信義區",
  },
  {
    id: "log2",
    bookingId: "booking1",
    propertyId: "1",
    propertyTitle: "台北市中心現代公寓",
    userId: "user1",
    userName: "張三",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    action: "unlock",
    status: "success",
    deviceInfo: "iPhone 14 Pro",
    location: "台北市信義區",
  },
  {
    id: "log3",
    bookingId: "booking1",
    propertyId: "1",
    propertyTitle: "台北市中心現代公寓",
    userId: "user1",
    userName: "張三",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
    action: "unlock",
    status: "failed",
    failureReason: "QR Code 已過期，請重新生成",
    deviceInfo: "iPhone 14 Pro",
    location: "台北市信義區",
  },
  {
    id: "log4",
    bookingId: "booking1",
    propertyId: "1",
    propertyTitle: "台北市中心現代公寓",
    userId: "user1",
    userName: "張三",
    timestamp: new Date(Date.now() - 25 * 60 * 60 * 1000), // 1 day ago
    action: "unlock",
    status: "success",
    deviceInfo: "iPhone 14 Pro",
    location: "台北市信義區",
  },
  {
    id: "log5",
    bookingId: "booking2",
    propertyId: "2",
    propertyTitle: "海景別墅度假屋",
    userId: "user2",
    userName: "李四",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
    action: "unlock",
    status: "success",
    deviceInfo: "Samsung Galaxy S23",
    location: "屏東縣墾丁",
  },
  {
    id: "log6",
    bookingId: "booking2",
    propertyId: "2",
    propertyTitle: "海景別墅度假屋",
    userId: "user2",
    userName: "李四",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000), // 3 hours ago
    action: "unlock",
    status: "failed",
    failureReason: "網路連線失敗，請檢查網路連線",
    deviceInfo: "Samsung Galaxy S23",
    location: "屏東縣墾丁",
  },
  {
    id: "log7",
    bookingId: "booking2",
    propertyId: "2",
    propertyTitle: "海景別墅度假屋",
    userId: "user2",
    userName: "李四",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
    action: "unlock",
    status: "success",
    deviceInfo: "Samsung Galaxy S23",
    location: "屏東縣墾丁",
  },
]
